### ISSUE TITLE
Getting error while installing the apk 

### ISSUE THREAD

**Issue by Shapa7276** [t0thkr1s/frida#1]
adb: failed to install app-debug.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]

**Comment by t0thkr1s** [comment]
👋

Thanks for opening this issue. I actually uploaded a test APK, so you have to use the `-t` switch allows you to install test APKs. The full command that you have to use is `adb install -t app-debug.apk`. Let me know, if you have further problems!

> -t: Allow test APKs to be installed. Gradle generates a test APK when you have only run or debugged your app or have used the Android Studio Build > Build APK command.

**Comment by Shapa7276** [comment]
Hello T0thk1s 

I am getting below error now 

![image](https://user-images.githubusercontent.com/41251016/91895885-961dea00-ecb5-11ea-8726-da49c83dc6e9.png)

**Comment by t0thkr1s** [comment]
Strange... I tested it with Genymotion and AVD, both worked flawlessly. What Android version are you trying to install on? The error message says that it couldn't verify the APK. I might have to rebuild the project and upload a new APK file.

**Comment by t0thkr1s** [comment]
Anyway, I signed the application. Now, you should be able to install it without the `-t` option.

**Comment by Shapa7276** [comment]
it worked. thank you
