### ISSUE TITLE
Please upload demo app(need to learn your all scripts at real time) sir, I need to learn this but apk is missing and now removed by you sir

### ISSUE THREAD

**Issue by PrabhuS007** [t0thkr1s/frida#7]
Please help me to learn sir,thanks you

**Comment by PrabhuS007** [comment]
S.kuttyprabhu@gmail.com my mail id, you can send also if any problem to upload it here means, thanks for sharing all

**Comment by t0thkr1s** [comment]
Hi!

I developed a completely new application for demo purposes. You can find that here: https://github.com/t0thkr1s/allsafe

Where did you find the reference for the old demo app? Thanks
